import 'package:flutter/material.dart';
import 'package:utrack/utils/constants/text_strings.dart';
import 'package:utrack/services/notification_service.dart';
import 'notif_elements.dart';
import 'notif_empty.dart';

class UNotificationScreen extends StatefulWidget {
  const UNotificationScreen({super.key});

  @override
  State<UNotificationScreen> createState() => _UNotificationScreenState();
}

class _UNotificationScreenState extends State<UNotificationScreen> {
  @override
  void initState() {
    super.initState();
    // Don't generate notifications on screen open to prevent duplicates
    // Notifications should be generated by background processes or manual refresh only
    print('📱 Notification screen opened - displaying existing notifications');
  }

  Future<void> _refreshNotifications() async {
    print('🔄 Notification screen: Smart refresh triggered...');
    
    // Get current notification count
    final notifications = await NotificationService.getNotificationsStream().first;
    
    if (notifications.isEmpty) {
      // If no notifications exist, generate them
      print('📝 No notifications found - generating new ones...');
      await NotificationService.generateLoanNotifications();
    } else {
      // If notifications exist, just refresh the display
      print('📱 Notifications exist - refreshing display only...');
      setState(() {});
    }
    
    print('✅ Smart refresh completed');
  }

  void _removeNotification(String notificationId) {
    NotificationService.deleteNotification(notificationId);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8F9FB),
      body: StreamBuilder<List<Map<String, dynamic>>>(
        stream: NotificationService.getNotificationsStream(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return Scaffold(
              backgroundColor: const Color(0xFFF8F9FB),
              appBar: _buildAppBar(context, 0),
              body: const Center(child: CircularProgressIndicator()),
            );
          }

          final notifications = snapshot.data ?? [];
          
          return Scaffold(
            backgroundColor: const Color(0xFFF8F9FB),
            appBar: _buildAppBar(context, notifications.length),
            body: notifications.isEmpty
                ? const EmptyNotificationWidget()
                : Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                    child: ListView.builder(
                      physics: const BouncingScrollPhysics(),
                      itemCount: notifications.length,
                      itemBuilder: (context, index) {
                        final n = notifications[index];
                        final data = n['data'] as Map<String, dynamic>? ?? {};
                        
                        switch (n["type"]) {
                        // -------- PAYMENT RELATED --------
                          case "overdue":
                            return SampleNotifCards.overduePayment(
                              borrowerName: data["lenderName"] ?? "Unknown",
                              amount: (data["amount"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "paymentReminder":
                            return SampleNotifCards.paymentReminder(
                              borrowerName: data["borrowerName"] ?? "Unknown",
                              amount: (data["amount"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "paymentReceived":
                            return SampleNotifCards.paymentReceived(
                              borrowerName: data["borrowerName"] ?? "Unknown",
                              amount: (data["amount"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "paymentSent":
                            return SampleNotifCards.paymentSent(
                              lenderName: data["lenderName"] ?? "Unknown",
                              amount: (data["amount"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "upcomingPayment":
                            return SampleNotifCards.upcomingPayment(
                              borrowerName: data["lenderName"] ?? "Unknown",
                              amount: (data["amount"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                            );

                        // -------- CREDIT SCORE --------
                          case "creditIncrease":
                            return SampleNotifCards.creditScoreIncrease(
                              percentage: (data["difference"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "creditDecrease":
                            return SampleNotifCards.creditScoreDecrease(
                              percentage: (data["difference"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                            );

                        // -------- BORROWING / LENDING --------
                          case "newBorrowRequest":
                            return SampleNotifCards.newBorrowRequest(
                              borrowerName: data["borrowerName"] ?? "Unknown",
                              amount: (data["amount"] as num?)?.toDouble() ?? 0.0,
                              onDelete: () => _removeNotification(n['id']),
                              context: context,
                              requestId: data["requestId"],
                              borrowerId: data["borrowerId"],
                              repaymentType: data["repaymentType"],
                              dueDate: data["dueDate"],
                              notes: data["notes"],
                            );
                          case "requestApproved":
                            return SampleNotifCards.requestApproved(
                              lenderName: data["lenderName"] ?? "Unknown",
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "requestRejected":
                            return SampleNotifCards.requestRejected(
                              lenderName: data["lenderName"] ?? "Unknown",
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "loanFullyRepaid":
                            return SampleNotifCards.loanFullyRepaid(
                              borrowerName: data["borrowerName"] ?? "Unknown",
                              onDelete: () => _removeNotification(n['id']),
                            );
                          case "loanDueSoon":
                            return SampleNotifCards.loanDueSoon(
                              borrowerName: data["borrowerName"] ?? "Unknown",
                              onDelete: () => _removeNotification(n['id']),
                            );

                          default:
                            return const SizedBox.shrink();
                        }
                      },
                    ),
                  ),
          );
        },
      ),
    );
  }

  AppBar _buildAppBar(BuildContext context, int notificationCount) {
    return AppBar(
      backgroundColor: Colors.white,
      elevation: 0,
      title: Row(
        children: [
          const Icon(Icons.notifications_outlined, color: Colors.black87),
          const SizedBox(width: 8),
          Text(
            UTexts.notif,
            style: Theme.of(context).textTheme.titleLarge!.copyWith(
              fontWeight: FontWeight.bold,
              color: Colors.black87,
            ),
          ),
          const SizedBox(width: 6),
          if (notificationCount > 0)
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
              decoration: BoxDecoration(
                color: Colors.redAccent,
                borderRadius: BorderRadius.circular(12),
              ),
              child: Text(
                notificationCount.toString(),
                style: const TextStyle(color: Colors.white, fontSize: 12),
              ),
            ),
        ],
      ),
      actions: [
        IconButton(
          icon: const Icon(Icons.refresh, color: Colors.black87),
          onPressed: () {
            print('🔄 Manual refresh triggered');
            _refreshNotifications();
          },
        ),
      ],
      centerTitle: false,
    );
  }
}