// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDseszkZEuxvnEfvfwvMGbnua6ff6mzFkE',
    appId: '1:888369758531:web:8672131aa4a00657506ff6',
    messagingSenderId: '888369758531',
    projectId: 'utrack-78928',
    authDomain: 'utrack-78928.firebaseapp.com',
    storageBucket: 'utrack-78928.firebasestorage.app',
    measurementId: 'G-5YLJXNN738',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0eRkCwNJMcq2Ol3TGjddCubXSETYUiZI',
    appId: '1:888369758531:android:0fa5b8d478637b16506ff6',
    messagingSenderId: '888369758531',
    projectId: 'utrack-78928',
    storageBucket: 'utrack-78928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7ZucLY3Xf1GYvJIIWceUMt3iaHoKYmA',
    appId: '1:888369758531:ios:902ab6ad77b3dca3506ff6',
    messagingSenderId: '888369758531',
    projectId: 'utrack-78928',
    storageBucket: 'utrack-78928.firebasestorage.app',
    iosBundleId: 'com.example.utrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM7ZucLY3Xf1GYvJIIWceUMt3iaHoKYmA',
    appId: '1:888369758531:ios:902ab6ad77b3dca3506ff6',
    messagingSenderId: '888369758531',
    projectId: 'utrack-78928',
    storageBucket: 'utrack-78928.firebasestorage.app',
    iosBundleId: 'com.example.utrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDseszkZEuxvnEfvfwvMGbnua6ff6mzFkE',
    appId: '1:888369758531:web:4b6b620c3ce9ae72506ff6',
    messagingSenderId: '888369758531',
    projectId: 'utrack-78928',
    authDomain: 'utrack-78928.firebaseapp.com',
    storageBucket: 'utrack-78928.firebasestorage.app',
    measurementId: 'G-BN5D6FMEV9',
  );
}
